name: Test on non-main branches

on:
  push:
    paths:
    - backend/src/**
    - backend/pom.xml
    - frontend/src/**
    - frontend/angular.json
    branches-ignore: [ main ]

jobs:
  build-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Server compile
        run: mvn clean compile
        working-directory: ./backend

  backend-unit-tests:
      runs-on: ubuntu-latest
      defaults: 
        run:
          working-directory: backend
      needs: build-backend
      
      steps:
        - uses: actions/checkout@v4

        - name: Set up JDK 21
          uses: actions/setup-java@v4
          with:
            distribution: temurin
            java-version: '21'

        - name: Run unit tests
          run: mvn test -Dgroups='unit'

  build-frontend:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm install
        working-directory: ./frontend

      - name: Compile frontend
        run: npm run build
        working-directory: ./frontend

  frontend-unit-tests:
    runs-on: ubuntu-latest
    needs: build-frontend
    defaults: 
      run:
        working-directory: frontend
    steps:
       - name: Checkout code
         uses: actions/checkout@v4

       - name: Setup Node.js
         uses: actions/setup-node@v3
         with:
           node-version: '20'

       - name: Install dependencies
         run: npm install
        
       - name: Run unit tests
         run: npx ng test --include "src/**/*.unit.spec.ts" --watch=false --browsers=ChromeHeadless --no-progress