name: Full tests on PR to main

on:
  pull_request:
    paths:
    - backend/src/**
    - backend/pom.xml
    - frontend/src/**
    - frontend/angular.json
    branches: [ main ]

jobs:
  build-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Server compile
        run: mvn clean compile
        working-directory: ./backend

  backend-unit-tests:
    runs-on: ubuntu-latest
    needs: build-backend
    defaults: 
      run:
        working-directory: backend
    
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - name: Run unit tests
        run: mvn test -Dgroups='unit'

  backend-integration-tests:
    runs-on: ubuntu-latest
    needs: backend-unit-tests
    defaults: 
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
      - name: Run integration tests
        run: mvn test -Dgroups='integration'

  backend-e2e-tests:
    runs-on: ubuntu-latest
    needs: backend-integration-tests
    defaults: 
      run:
        working-directory: backend
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - name: Start frontend
        run: |
          cd ../frontend
          npm install
          npm run start-test -- --port 4200 &
          sleep 20

      - name: Run system tests
        run: mvn test -Dgroups='e2e'

  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install
        working-directory: backend
      
      - name: Frontend compile
        run: npm run build
        working-directory: ./frontend
  
  frontend-unit-tests:
    runs-on: ubuntu-latest
    needs: build-frontend
    defaults: 
      run:
        working-directory: frontend
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Run unit tests
        run: npx ng test --include "src/**/*.unit.spec.ts" --watch=false --browsers=ChromeHeadless --no-progress
      

  frontend-integration-tests:
    runs-on: ubuntu-latest
    needs: frontend-unit-tests
    defaults: 
      run:
        working-directory: frontend
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Start backend server
        run: |
          cd ../backend
          mvn spring-boot:run &
          sleep 30

      - name: Install Dependencies
        run: npm install

      - name: Run integration tests
        run: npx ng test --include "src/**/*.integration.spec.ts" --watch=false --browsers=ChromeHeadless --no-progress

       