name: Test on non-main branches (client + server)

on:
  push:
    paths:
    - backend/src/**
    - backend/pom.xml
    - frontend/src/**
    - frontend/angular.json
    branches-ignore: [ main ]

jobs:
  backend-tests:
    runs-on: ubuntu-latest
    defaults: 
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Run unit tests
        run: mvn test -Dgroups='unit'
  frontend-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run: npx ng test --include "src/**/*.unit.spec.ts"