name: Full tests on PR to main

on:
  pull_request:
    paths:
    - backend/src/**
    - backend/pom.xml
    - frontend/src/**
    - frontend/angular.json
    branches: [ main ]

jobs:

  backend-tests:
    runs-on: ubuntu-latest
    defaults: 
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Run unit tests
        run: mvn test -Dgroups='unit'

      - name: Run integration tests
        run: mvn test -Dgroups='integration'

      - name: Run system tests
        run: mvn test -Dgroups='e2e'

  frontend-tests:
    runs-on: ubuntu-latest
    defaults: 
      run:
        working-directory: frontend
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Start backend server
        run: |
          cd ../backend
          mvn spring-boot:run &
          sleep 30

      - name: Install Dependencies
        run: npm install

      - name: Run unit tests
        run: npx ng test --include "src/**/*.unit.spec.ts" --watch=false --browsers=ChromeHeadless --no-progress

      - name: Run integration tests
        run: npx ng test --include "src/**/*.integration.spec.ts" --watch=false --browsers=ChromeHeadless --no-progress

       